org: mcastroa
service: api-s3

provider:
  name: aws
  runtime: python3.13	
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  # Default memory size for functions (default: 256MB)
  memorySize: 1024
  timeout: 20
  iam:
    role: arn:aws:iam::016748221635:role/LabRole
  environment:
    STAGE: ${self:provider.stage}

functions:
  lista_buckets:
    handler: lista_buckets.lambda_handler
    memorySize: 512
    events:
      - http:
          path: /s3/lista-buckets
          method: get
          cors: true
          integration: lambda
          authorizer: false
  lista_objetos_bucket:
    handler: lista_objetos_bucket.lambda_handler
    events:
      - http:
          path: /s3/bucket/lista-objetos
          method: post
          cors: true
          integration: lambda
          authorizer: false
  crear_bucket:
    handler: crear_bucket.lambda_handler
    events:
      - http:
          path: /s3/crear-bucket
          method: post
          cors: true
          integration: lambda
          authorizer: false
  crear_directorio:
    handler: crear_directorio.lambda_handler
    events:
      - http:
          path: /s3/crear-directorio
          method: post
          cors: true
          integration: lambda
          authorizer: false
  subir_archivo:
    handler: subir_archivo.lambda_handler
    events:
      - http:
          path: /s3/subir-archivo
          method: post
          cors: true
          integration: lambda
          authorizer: false
